# Generated by Django 5.0.6 on 2024-05-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_ticker_reservation_alter_ticker_performance"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ticker",
            new_name="Ticket",
        ),
    ]
