# Generated by Django 5.0.6 on 2024-05-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_rename_ticker_ticket"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="sear",
            new_name="seat",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "performance")},
        ),
    ]
