# Generated by Django 5.0.6 on 2024-05-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0005_rename_sear_ticket_seat_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
    ]
